### ISSUE TITLE
bppsuite - manual

### ISSUE THREAD

**Issue by kullrich** [BioPP/bppsuite#12]
Could you please change for the `bpppopstats` program one doc option.

In the manual it is written `CodonSitesStatistics`, however it seems to be spelled `CodonSiteStatistics`

https://github.com/BioPP/bppsuite/blob/master/doc/bppsuite.texi

```
@item CodonSitesStatistics
Generate a table with codon-site specifics statistics, including:
```

into

```
@item CodonSiteStatistics
Generate a table with codon-site specifics statistics, including:
```

Thank you in anticipation

Best regards

Kristian Ullrich

**Comment by jydu** [comment]
Done.
