### ISSUE TITLE
CodonSiteStatistics - output.file

### ISSUE THREAD

**Issue by kullrich** [BioPP/bppsuite#13]
Hi,

I could not specify an `output.file` via the cmd arguments and it seems that an argument within the option params could not be set.

In `bash` it seems to be not supported to create a variable with a `.` inside the name:

see `bash` export man

```
   name   A  word  consisting  only  of alphanumeric characters and under‐
          scores, and beginning with an alphabetic character or an  under‐
          score.  Also referred to as an identifier.
```

As a work-around I now changed the following lines of and re-compiled:

https://github.com/BioPP/bppsuite/blob/master/bppSuite/bppPopStats.cpp

```
      // +-----------------------+
      // | Codon site statistics |
      // +-----------------------+
      else if (cmdName == "CodonSiteStatistics")
      {
        if (!codonAlphabet) {
          throw Exception("CodonSiteStatstics can only be used with a codon alignment. Check the input alphabet!");
        }
        string path = ApplicationTools::getAFilePath("output.file", cmdArgs, true, false);
```

into

```
      // +-----------------------+
      // | Codon site statistics |
      // +-----------------------+
      else if (cmdName == "CodonSiteStatistics")
      {
        if (!codonAlphabet) {
          throw Exception("CodonSiteStatstics can only be used with a codon alignment. Check the input alphabet!");
        }
        string path = ApplicationTools::getAFilePath("output.file", bpppopstats.getParams(), true, false);
```

Now, an output.file argument can be set in the option params file.

Maybe think of a better explanation in the manual, how to set with command arguments.

```
WARNING!!! Parameter output.file not specified. Default used instead: none
You must specify a file for this parameter: output.file
```

Thank you in anticipation

Best regards

Kristian Ullrich

**Comment by lgueguen** [comment]
Hi Kristian, 

thanks for the work-around, I fixed it.

Also, I do not really understand what you mean about a better explanation in the manual. It seems to 
me rather clear, the problem with the dot names is more from bash, and not from bppsuite?

Cheers,
Laurent

**Comment by kullrich** [comment]
Yes,
the better explanation was meant to be related to the **non-functional output.file** parameter.

For me, both,  the **params config** and a **bash variable** were not functional and in this respect the warning message was not explicit enough how to fix it and **I needed to recode in the cpp code to make it functional**.

Now, if everything works fine even within the params config file than the warning message is enough.

Best regards
