### ISSUE TITLE
bppsuite 3.0.0 relies on not yet published bpp-phyl

### ISSUE THREAD

**Issue by tillea** [BioPP/bppsuite#14]
Hi,
I tried to update the bppsuite package in Debian.  When I try to build bppsuite 3.0.0 but it is seeking header files in different places than in libbpp-phyl 2.4.1 which is packaged for Debian. For instance the header files that reside in Bpp/Phyl/Tree.h are seeked in Bpp/Phyl/Tree/Tree.h.  I suspect you are using a higher version of the library but this is not yet tagged on Github.
Kind regards, Andreas.

**Comment by jydu** [comment]
Hi Andreas,

bppSuite 3.00 is not yet officially released (the "release" on GitHub is labelled "newlik" and was an alternate developmental version. It we will be removed as we have finally merged the development branches into master. We are still debugging version 3.00 but expect to be able to do an official release soon. V300 will come with non-backward compatible interface, and I was thinking that the package should be renamed as libbpp-core3, libbpp-seq3, etc, right?
The current debian packages could be updated, but from the branch 'rel299', which contains the latest freeze of the master branch before it switched to v3.00.

Best regards,

Julien.

**Comment by tillea** [comment]
Am Tue, Feb 15, 2022 at 09:58:21PM -0800 schrieb Julien Y. Dutheil:
> bppSuite 3.00 is not yet officially released (the "release" on GitHub is labelled "newlik" and was an alternate developmental version. It we will be removed as we have finally merged the development branches into master. We are still debugging version 3.00 but expect to be able to do an official release soon. V300 will come with non-backward compatible interface, and I was thinking that the package should be renamed as libbpp-core3, libbpp-seq3, etc, right?
> The current debian packages could be updated, but from the branch 'rel299', which contains the latest freeze of the master branch before it switched to v3.00.

From my point of view code that is tagged (v3.0.0) is a "release" and code that just resides in a branch (rel299) and has no tag is not a release.  It would help if you would find different tag name - for instance v3.0.0~alpha or something like this - to tell users that this is no production ready code.

Kind regards, Andreas.
