### ISSUE TITLE
sth wrong with Bpp/Version.h when installing

### ISSUE THREAD

**Issue by jungleblack007** [BioPP/bppsuite#20]
Sorry, I met the mistakes when I compile the software, how can I make it?

[  3%] Building CXX object CMakeFiles/bppml.dir/bppML.o
/public/home/Wanggs/software/bppsuite-master/bppSuite/bppML.cpp:13:10: fatal error: Bpp/Version.h: No such file or directory
   13 | #include <Bpp/Version.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/bppml.dir/bppML.o] Error1
make[1]: *** [CMakeFiles/bppml.dir/all] Error 2
make: *** [all] Error 2

**Comment by jydu** [comment]
Hi, did you install the Bio++ libraries? The easiest is to install bppSuite and the bpp libraries in the same path (passing the same `-DCMAKE_INSTALL_PREFIX=[PATH]` option to make, for instance with [PATH]=$HOME/.local). 

Julien.

**Comment by lgueguen** [comment]
Nothing new. Closing
