### ISSUE TITLE
bppseqgen expected to ignore branch length from root to mrca?

### ISSUE THREAD

**Issue by psathyrella** [BioPP/bppsuite#3]
It appears that bppseqgen doesn't mutate according to the distance between root and mrca. For instance using a tree like:

`(t1:0.001,t2:0.001):0.1;`

results in two essentially unmutated sequences. Adding a dummy leaf `xxx` branched from root to this tree, on the other hand, results in the expected mutation rates:

`((t1:0.001,t2:0.001):0.1,xxx:0.101):0.0;`

This seems like unexpected behavior to me, but perhaps I'm missing something?

**Comment by lgueguen** [comment]
Hi,

yes indeed, the branch leading from root to mrca is not considered. The original point of bppseqgen is to simulate processes, to check a which point likelihood inference (with bppml in our case) is able to find the models used for simulation. But,  it is not possible to infer anything on a branch between root and mrca, so it is cancelled in bppseqgen, and the root is at the mrca. 

Cheers,
Laurent

**Comment by psathyrella** [comment]
Ok, that makes sense, thanks for the explanation. My use case requires its consideration, but I can get around it by just adding the extra leaf and then ignoring it.
